version: 2

builds:
  - main: .
    binary: td
    ldflags:
      - -s -w -X main.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
      - CHANGELOG.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

homebrew_casks:
  - name: td
    homepage: https://github.com/marcus/td
    description: Task management CLI for AI-assisted development
    directory: Casks
    repository:
      owner: marcus
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
