#!/usr/bin/env bash
# commit-msg hook for td
# Install: make install-hooks  (or: ln -sf ../../scripts/commit-msg.sh .git/hooks/commit-msg)
set -euo pipefail

MSG_FILE=${1:?commit message file required}

trim() {
  local value=${1-}
  value=$(printf '%s' "$value" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')
  printf '%s' "$value"
}

squeeze_spaces() {
  local value=${1-}
  value=$(printf '%s' "$value" | tr '\t' ' ' | sed -E 's/[[:space:]]+/ /g')
  trim "$value"
}

lowercase() {
  printf '%s' "${1-}" | tr '[:upper:]' '[:lower:]'
}

fail_invalid() {
  cat >&2 <<'EOF'
td commit-msg: commit subject must look like:
  type: summary (td-<id>)

Examples:
  feat: add commit message hook (td-a1b2)
  fix: preserve commit trailers (td-c3d4)

Allowed exceptions:
  - merge/revert/fixup/squash commits generated by git
  - automated release bump commits: td: bump to vX.Y.Z
EOF
  exit 1
}

if [[ ! -f "$MSG_FILE" ]]; then
  echo "td commit-msg: message file not found: $MSG_FILE" >&2
  exit 1
fi

subject=$(sed -n '1p' "$MSG_FILE")
rest=$(tail -n +2 "$MSG_FILE" 2>/dev/null || true)
subject=$(squeeze_spaces "$subject")

if [[ -z "$subject" ]]; then
  fail_invalid
fi

case "$subject" in
  Merge\ *|Revert\ *|fixup!\ *|squash!\ *)
    exit 0
    ;;
esac

if [[ "$subject" =~ ^[Tt][Dd][[:space:]]*:[[:space:]]*bump[[:space:]]+to[[:space:]]+(v[0-9]+(\.[0-9]+){2}([-.][[:alnum:]]+)*)$ ]]; then
  normalized_subject="td: bump to ${BASH_REMATCH[1]}"
else
  if [[ ! "$subject" =~ ^([[:alpha:]][[:alnum:]-]*)[[:space:]]*:[[:space:]]*(.+)$ ]]; then
    fail_invalid
  fi

  commit_type=$(lowercase "${BASH_REMATCH[1]}")
  remainder=$(squeeze_spaces "${BASH_REMATCH[2]}")
  token=""
  summary=""

  if [[ "$remainder" =~ ^(.*[^[:space:]])[[:space:]]*\(([Tt][Dd]-[[:alnum:]][[:alnum:]-]*)\)[[:space:]]*$ ]]; then
    summary=$(squeeze_spaces "${BASH_REMATCH[1]}")
    token=$(lowercase "${BASH_REMATCH[2]}")
  elif [[ "$remainder" =~ ^(.*[^[:space:]])[[:space:]]+([Tt][Dd]-[[:alnum:]][[:alnum:]-]*)[[:space:]]*$ ]]; then
    summary=$(squeeze_spaces "${BASH_REMATCH[1]}")
    token=$(lowercase "${BASH_REMATCH[2]}")
  fi

  if [[ -z "$token" || -z "$summary" ]]; then
    fail_invalid
  fi

  normalized_subject="${commit_type}: ${summary} (${token})"
fi

tmp=$(mktemp)
printf '%s\n' "$normalized_subject" > "$tmp"
if [[ -n "$rest" ]]; then
  printf '%s\n' "$rest" >> "$tmp"
fi
mv "$tmp" "$MSG_FILE"
