#!/usr/bin/env bash
# commit-msg hook for td
# Installed by: make install-hooks
# Manual install: ln -sf ../../scripts/commit-msg.sh .git/hooks/commit-msg
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <commit-message-file>" >&2
  exit 2
fi

msg_file=$1

if [[ ! -f "$msg_file" ]]; then
  echo "commit-msg: file not found: $msg_file" >&2
  exit 2
fi

clean_message=$(git stripspace --strip-comments <"$msg_file")
subject=$(printf '%s\n' "$clean_message" | sed -n '1p')

if [[ -z "$subject" ]]; then
  cat >&2 <<'EOF'
Commit message is empty.

Use the standard task-work format:
  <type>: <summary> (td-<id>)

Example:
  feat: normalize commit messages (td-abc123)
EOF
  exit 1
fi

task_pattern='^(feat|fix|docs|chore|refactor|test|perf|build|ci|style|revert)(\([a-z0-9._/-]+\))?: .+ \(td-[a-z0-9]+\)$'
exception_pattern='^(Merge( branch| remote-tracking branch| pull request).+|Revert ".+"|(fixup|squash)! .+|docs: Update changelog for v[0-9]+\.[0-9]+\.[0-9]+|td: bump to v[0-9]+\.[0-9]+\.[0-9]+)$'

if [[ "$subject" =~ $task_pattern ]] || [[ "$subject" =~ $exception_pattern ]]; then
  exit 0
fi

cat >&2 <<EOF
Commit subject does not match td's standard format:
  $subject

Expected:
  <type>: <summary> (td-<id>)

Examples:
  feat: normalize commit messages (td-abc123)
  fix(parser): handle empty commit subject (td-9f2e1a)

Allowed exceptions:
  docs: Update changelog for vX.Y.Z
  td: bump to vX.Y.Z
  Merge / Revert / fixup! / squash! messages generated by Git

If this commit maps to task work, include the task id at the end of the subject.
EOF
exit 1
