#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
HOOK="$REPO_DIR/scripts/commit-msg.sh"

TMPDIR_ROOT=$(mktemp -d "${TMPDIR:-/tmp}/td-commit-msg-test-XXXX")
trap 'rm -rf "$TMPDIR_ROOT"' EXIT

PASS_COUNT=0

assert_file_matches() {
  local label="$1"
  local file="$2"
  local expected="$3"
  local expected_file="$TMPDIR_ROOT/expected-${PASS_COUNT}.txt"

  printf '%s' "$expected" > "$expected_file"

  if ! cmp -s "$file" "$expected_file"; then
    echo "FAIL: $label" >&2
    diff -u "$expected_file" "$file" >&2 || true
    exit 1
  fi
}

run_hook_ok() {
  local label="$1"
  local input="$2"
  local expected="$3"
  local file="$TMPDIR_ROOT/${PASS_COUNT}.txt"
  local stderr_file="$TMPDIR_ROOT/${PASS_COUNT}.stderr"

  printf '%s' "$input" > "$file"
  "$HOOK" "$file" 2> "$stderr_file"

  assert_file_matches "$label" "$file" "$expected"

  PASS_COUNT=$((PASS_COUNT + 1))
  echo "PASS: $label"
}

run_hook_fail() {
  local label="$1"
  local input="$2"
  local expected_error="$3"
  local file="$TMPDIR_ROOT/${PASS_COUNT}.txt"
  local stderr_file="$TMPDIR_ROOT/${PASS_COUNT}.stderr"

  printf '%s' "$input" > "$file"

  if "$HOOK" "$file" > /dev/null 2> "$stderr_file"; then
    echo "FAIL: $label" >&2
    echo "Expected hook failure" >&2
    exit 1
  fi

  local actual_error
  actual_error=$(cat "$stderr_file")
  assert_file_matches "$label (file unchanged)" "$file" "$input"

  if [[ "$actual_error" != *"$expected_error"* ]]; then
    echo "FAIL: $label" >&2
    echo "Expected error containing: $expected_error" >&2
    echo "Actual stderr:" >&2
    printf '%s\n' "$actual_error" >&2
    exit 1
  fi

  PASS_COUNT=$((PASS_COUNT + 1))
  echo "PASS: $label"
}

run_hook_ok "canonical pass-through" \
  $'feat: add issue detail status line (td-79fac9)\n\nBody stays here.\n' \
  $'feat: add issue detail status line (td-79fac9)\n\nBody stays here.\n'

run_hook_ok "canonical custom type pass-through" \
  $'security: harden parser for malformed trailers\n' \
  $'security: harden parser for malformed trailers\n'

run_hook_ok "safe rewrite to canonical format" \
  $'Docs - Update changelog\n' \
  $'docs: update changelog\n'

run_hook_ok "scope normalization" \
  $'FIX( Monitor_UI ) : Tighten spacing.\n' \
  $'fix(monitor-ui): tighten spacing\n'

run_hook_ok "td suffix normalization" \
  $'Chore( Release ) - Update Homebrew tap for v1.2.3 ( TD-527BD4-0006 )\n' \
  $'chore(release): update Homebrew tap for v1.2.3 (td-527bd4-0006)\n'

run_hook_ok "body and trailer preservation with commented template header" \
  $'# Please enter the commit message for your changes.\n\nDocs - Update changelog ( TD-A1B2 )\n\nKeep this body line exactly.\n\nNightshift-Task: commit-normalize\nNightshift-Ref: https://github.com/marcus/nightshift\n' \
  $'# Please enter the commit message for your changes.\n\ndocs: update changelog (td-a1b2)\n\nKeep this body line exactly.\n\nNightshift-Task: commit-normalize\nNightshift-Ref: https://github.com/marcus/nightshift\n'

run_hook_ok "human-written merge prefix gets normalized" \
  $'Merge - Update changelog\n' \
  $'merge: update changelog\n'

run_hook_ok "human-written revert prefix gets normalized" \
  $'Revert: cleanup generated files.\n' \
  $'revert: cleanup generated files\n'

for generated_subject in \
  "Merge branch 'main' into feature/test" \
  "Merge pull request #122 from marcus/feat/commit-message-normalizer-v11" \
  "fixup! feat: add issue detail status line (td-79fac9)" \
  "squash! docs: update changelog" \
  'Revert "feat: add issue detail status line (td-79fac9)"'
do
  run_hook_ok "git-generated pass-through: $generated_subject" \
    "$generated_subject"$'\n\nGenerated by Git.\n' \
    "$generated_subject"$'\n\nGenerated by Git.\n'
done

run_hook_fail "reject malformed td suffix" \
  $'feat: add parser (td-)\n' \
  "malformed td suffix"

run_hook_fail "reject ambiguous bare td suffix" \
  $'feat: add parser td-a1b2\n' \
  "ambiguous td suffix"

run_hook_fail "reject unparseable subject" \
  $'Implement commit normalizer\n' \
  "commit subject must match"

echo "PASS: all $PASS_COUNT commit-msg normalization checks"
